// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jewelry.Data.Models;

public partial class SiCompany
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string CompanyAddress { get; set; }

    public string EmailAddress { get; set; }

    public string Hotline { get; set; }

    public string ZipCode { get; set; }

    public int? NoOfYearsInBusiness { get; set; }

    public string Policy { get; set; }

    public int? EmployeeNum { get; set; }

    public string ContactPerson { get; set; }

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();
}