// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jewelry.Data.Models;

public partial class SiCustomer
{
    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string AlterContact { get; set; }

    public string Address { get; set; }

    public bool? Gender { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string Country { get; set; }

    public string Job { get; set; }

    public string Email { get; set; }

    public string ZipCode { get; set; }


    public virtual ICollection<SiOrder> SiOrders { get; set; } = new List<SiOrder>();
}