// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Jewelry.Data.Models;

public partial class SiProduct
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public int? CategoryId { get; set; }

    public string Description { get; set; }

    public string Barcode { get; set; }

    public double? Weight { get; set; }

    public int? CostPrice { get; set; }

    public int? GoldPrice { get; set; }

    public int? LaborCost { get; set; }

    public int? StoneCost { get; set; }

    public double? SellPriceRatio { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}